module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v3.0-beta-146-g2b8ac09"

gitRepo : String 
gitRepo = "https://github.com/kgashok/elm-simple-json-decoding"

