module Version exposing (..)

{-| This file is auto-generated by the Python script version.py.
-}


version : String
version =
    "v3.5-beta-45-g215b67b"


gitRepo : String
gitRepo =
    "https://github.com/kgashok/elm-simple-json-decoding"
