module Main exposing (..) -- where
import Expect exposing (Expectation)
import Fuzz exposing (Fuzzer, int, list, string)
import Test exposing (..)

--import ElmTest exposing (..)

import Model exposing (..)

testm : Model 
testm =  {initialModel | gRoom = 
    {id = "570a5925187bb6f0eadebf05", name="", userCount=0} }


createMember : String -> Int -> Member 
createMember name points = 
  { uname  = name
  , points = points
  }

memberList : List Member
memberList = 
    [ createMember "kgashok" 200
    , createMember "sudhar" 100
    , createMember "ramya" 150
    ]

{-pointsData : Int -> Time -> Int -> Cdata -}

historyS : List Cdata 
historyS = 
    [ pointsData 110 9000 0
    , pointsData 120 15000 9000
    , pointsData 122 16000 10000
    ]


historyR : List Cdata 
historyR = 
    [ pointsData 150 9000 0
    , pointsData 170 15500 9000
    , pointsData 222 17000 10000
    ]

historyA : List Cdata 
historyA = 
    [ pointsData 220 9000 0
    , pointsData 222 10000 9000
    , pointsData 226 11000 10000
    , pointsData 229 11000 10000
    ]


{- Both the below needed to be included in the model-}
{-In Elm repl inHours 2592000000 = 720 hours  or 30 days-}
cutOff : Float
cutOff = 10000 


assignHistory : List Cdata -> Camper -> Camper 
assignHistory data camper = 
    {camper| chist = data} 


createCampersFromMembers : List Member -> List Camper 
createCampersFromMembers mList = 
  let 
    cList = List.map (createCamper 0) memberList
  in 
    List.map2 assignHistory [historyA, historyS, historyR] cList


dinfo : { c | last : { b | points : a }, uname : String } -> String
dinfo {uname, last} = 
    uname ++ " " ++ (toString last.points)


{- contains a portion of the output that is generated by the FCC bot 
-}
url : String 
url = "http://myjson.com/2dzdj"


all : Test 
all =
  let 
    clist         = createCampersFromMembers memberList
    dummy         = createCamper 0 {uname = "NA", points = 0}
    first         = List.head clist |> Maybe.withDefault dummy 
    sortOut       = List.map dinfo (sortBasedOnHistory2 20000 20000 clist )
    sortOutWithCO = List.map dinfo (sortBasedOnHistory2 20000 cutOff clist)
    --todo "Implement our first test. See http://package.elm-lang.org/packages/elm-community/elm-test/latest for how to do this!"
  in   
    describe "Fcc Test Suite" 
      [describe "Unit test examples"
        [ test "zero" <| \() -> Expect.equal 0 0
        , test "truth" <| \() -> Expect.true "the truth" True
        , test "booleans" <| \() -> Expect.notEqual True False
        , test "pass" <| \() -> Expect.equal [0, 30, 60, 90, 120, 150, 180] (skipList 170)
        , test "history" <| \() -> Expect.equal historyA first.chist
        , test "sort" <| \() ->
            Expect.equal ["ramya 150", "sudhar 100", "kgashok 200"] sortOut
        , test "sortcut" <| \() -> 
            Expect.equal ["ramya 150", "kgashok 200", "sudhar 100"] sortOutWithCO
        ]
      ]



{--
consoleTests : Test
consoleTests =
    suite "All Tests" tests

main : Program Never
main =
    runSuite consoleTests
    --runSuiteHtml consoleTests
    
--}